package com.osrs.server.network.codec

enum class ServerProt(val opcode: Int, val size: Int) {
    PLAYER_INFO(79, -2),
    NPC_INFO_SMALL_VIEWPORT(61, -2),
    NPC_INFO_LARGE_VIEWPORT(32, -2),
    REBUILD_NORMAL(73, -2),
    REBUILD_REGION(3, -2),
    MAP_ANIM(55, 6),
    MAP_PROJANIM(56, 8),
    OBJ_ADD(26, 5),
    OBJ_DEL(76, 3),
    OBJ_COUNT(15, 7),
    LOC_ADD_CHANGE(114, 4),
    LOC_DEL(12, 2),
    LOC_ANIM(85, 4),
    IF_OPENTOP(30, 2),
    IF_OPENSUB(82, 8),
    IF_CLOSESUB(92, 4),
    IF_MOVESUB(52, 8),
    IF_SETANGLE(8, 10),
    IF_SETANIM(38, 8),
    IF_SETCOLOUR(60, 6),
    IF_SETHIDE(70, 5),
    IF_SETMODEL(4, 8),
    IF_SETNPCHEAD(34, 6),
    IF_SETOBJECT(10, 8),
    IF_SETPLAYERHEAD(45, 4),
    IF_SETPOSITION(24, 8),
    IF_SETSCROLLPOS(75, 6),
    IF_SETTEXT(48, -1),
    CLIENTSCRIPT(49, -2),
    FRIENDLIST_LOADED(22, 0),
    UPDATE_RUNWEIGHT(120, 2),
    UPDATE_STAT(46, 6),
    RESET_STAT(68, 1),
    UPDATE_RUNORG(87, 1),
    UPDATE_REBOOT_TIMER(65, 4),
    UPDATE_INV_FULL(41, -2),
    UPDATE_INV_PARTIAL(23, -2),
    UPDATE_INV_STOP_TRANSMIT(16, 0),
    VARP_SMALL(62, 3),
    VARP_LARGE(2, 6),
    VARCLIENT_SMALL(80, 3),
    VARCLIENT_LARGE(71, 6),
    RESET_CLIENT_VARCACHE(40, 0),
    VARBIT_SMALL(53, 3),
    VARBIT_LARGE(83, 6),
    MESSAGE_GAME(67, -1),
    MESSAGE_PUBLIC(54, -1),
    MESSAGE_PRIVATE(43, -2),
    MESSAGE_PRIVATE_ECHO(5, -1),
    MESSAGE_FRIEND_CHANNEL(20, -1),
    MESSAGE_CLAN_CHANNEL(44, -1),
    MESSAGE_CLAN_CHANNEL_SYSTEM(63, -1),
    UPDATE_FRIENDLIST(1, -1),
    UPDATE_IGNORELIST(72, -1),
    UPDATE_FRIEND_CHAT_CHANNEL_FULL(7, -2),
    UPDATE_FRIEND_CHAT_CHANNEL_PARTIAL(9, -2),
    CAM_LOOKAT(81, 6),
    CAM_MOVETO(91, 6),
    CAM_RESET(78, 0),
    CAM_SHAKE(99, 4),
    CAM_SMOOTHRESET(25, 0),
    MIDI_SONG(28, 2),
    MIDI_JINGLE(31, 4),
    SYNTH_SOUND(58, 5),
    RESET_ANIMS(17, 0),
    HINT_ARROW(107, 6),
    CLEAR_HINT_ARROW(101, 2),
    UPDATE_ZONE_PARTIAL_ENCLOSED(88, -2),
    UPDATE_ZONE_PARTIAL_FOLLOWS(36, -2),
    UPDATE_ZONE_FULL_FOLLOWS(90, -2),
    LOGOUT_FULL(96, 0),
    LOGOUT_TRANSFER(116, -1),
    SERVER_TICK_END(97, 0),
    SET_PLAYER_OP(100, -1),
    PLAYER_SPOTANIM(14, 8),
    UPDATE_CLAN_SETTINGS_FULL(74, -2),
    UPDATE_CLAN_CHANNEL_FULL(86, -2),
    URL_OPEN(89, -1),
    WORLDLIST_FETCH_REPLY(69, -2),
    ;

    companion object {
        private val byOpcode = values().associateBy { it.opcode }
        fun fromOpcode(opcode: Int): ServerProt? = byOpcode[opcode]
        fun validateNoDuplicates(): List<String> {
            val seen = mutableMapOf<Int, MutableList<String>>()
            for (prot in values()) {
                seen.getOrPut(prot.opcode) { mutableListOf() }.add(prot.name)
            }
            return seen.filter { it.value.size > 1 }
                .map { (opcode, names) -> "Opcode $opcode conflict: ${names.joinToString(", ")}" }
        }
    }
}

enum class ClientProt(val opcode: Int, val size: Int) {
    MOVE_MINIMAPCLICK(49, 18),
    MOVE_GAMECLICK(39, 18),
    IF_BUTTON1(30, 8),
    IF_BUTTON2(52, 8),
    IF_BUTTON3(33, 8),
    IF_BUTTON4(80, 8),
    IF_BUTTON5(14, 8),
    IF_BUTTON6(72, 8),
    IF_BUTTON7(93, 8),
    IF_BUTTON8(34, 8),
    IF_BUTTON9(65, 8),
    IF_BUTTON10(4, 8),
    CLOSE_MODAL(21, 0),
    OPOBJ1(54, 7),
    OPOBJ2(10, 7),
    OPOBJ3(20, 7),
    OPOBJ4(25, 7),
    OPOBJ5(29, 7),
    OPOBJT(38, 15),
    OPNPC1(84, 3),
    OPNPC2(28, 3),
    OPNPC3(23, 3),
    OPNPC4(16, 3),
    OPNPC5(3, 3),
    OPNPCT(47, 11),
    OPPLAYER1(77, 3),
    OPPLAYER2(24, 3),
    OPPLAYER3(40, 3),
    OPPLAYER4(79, 3),
    OPPLAYER5(87, 3),
    OPPLAYER6(68, 3),
    OPPLAYER7(17, 3),
    OPPLAYER8(32, 3),
    OPPLAYERT(7, 11),
    OPLOC1(41, 7),
    OPLOC2(43, 7),
    OPLOC3(11, 7),
    OPLOC4(59, 7),
    OPLOC5(1, 7),
    OPLOCT(55, 15),
    OPITEM1(90, 7),
    OPITEM2(35, 7),
    OPITEM3(53, 7),
    OPITEM4(67, 7),
    OPITEM5(9, 7),
    OPITEMT(36, 15),
    OPHELDT(89, 15),
    CHAT_SEND_PUBLIC(78, -1),
    CHAT_SEND_PRIVATE(57, -1),
    CHAT_COMMAND(71, -1),
    CHAT_SET_FILTER(45, 3),
    FRIEND_CHAT_JOIN(64, -1),
    FRIEND_CHAT_LEAVE(48, 0),
    FRIEND_CHAT_KICK(75, -1),
    FRIENDS_ADD(88, -1),
    FRIENDS_DEL(51, -1),
    IGNORE_ADD(74, -1),
    IGNORE_DEL(19, -1),
    WINDOW_STATUS(22, 5),
    CAMERA_ROTATION(86, 4),
    CLIENT_CHEAT(85, -1),
    CLANS_SETRANK(42, -1),
    CLAN_SETTINGS_SETFORM(26, -1),
    COUNTDIALOG(82, 4),
    RESUME_PAUSEBUTTON(44, 0),
    RESUME_P_NAMEDIALOG(96, -1),
    RESUME_P_OBJDIALOG(60, 4),
    RESUME_P_STRINGDIALOG(73, -1),
    RESUME_P_COUNTDIALOG(62, 4),
    PING(5, 0),
    SEND_SNAPSHOT(50, 0),
    EVENT_MOUSE_CLICK(27, 6),
    EVENT_MOUSE_MOVE(81, -1),
    EVENT_KEYBOARD(15, -1),
    EVENT_NATIVE_MOUSE_CLICK(13, 6),
    ANTICHEAT_CLIENTSYNC(92, 4),
    ;

    companion object {
        private val byOpcode = values().associateBy { it.opcode }
        fun fromOpcode(opcode: Int): ClientProt? = byOpcode[opcode]
        fun validateNoDuplicates(): List<String> {
            val seen = mutableMapOf<Int, MutableList<String>>()
            for (prot in values()) {
                seen.getOrPut(prot.opcode) { mutableListOf() }.add(prot.name)
            }
            return seen.filter { it.value.size > 1 }
                .map { (opcode, names) -> "Opcode $opcode conflict: ${names.joinToString(", ")}" }
        }
    }
}
